module(
    name = "airlance",
    version = "1.0",
)

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

bazel_dep(name = "rules_apple", version = "4.4.0", repo_name = "build_bazel_rules_apple")
bazel_dep(name = "rules_swift", version = "3.6.0", repo_name = "build_bazel_rules_swift")
bazel_dep(name = "rules_xcodeproj", version = "4.1.0")

http_file(
    name = "cmake_tar_gz",
    urls = ["https://github.com/Kitware/CMake/releases/download/v4.4.2/cmake-4.4.2-macos-universal.tar.gz"],
    sha256 = "800fc86838e913fff969b499886c80baeb4ccfd00f0e39906b34aa334f39ab6c",
)