// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public enum Protocol__Body: UInt8, FlatbuffersVectorInitializable, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case ping = 1
  case pong = 2
  case newsession = 3
  case resumesession = 4
  case registeraccount = 5
  case registeraccountack = 6
  case confirmemailcode = 7
  case confirmemailcodeack = 8
  case error = 9
  case newsessionack = 10
  case resumesessionack = 11
  case sendmessage = 12
  case sendmessageack = 13
  case messageupdate = 14
  case getdifference = 15
  case differenceack = 16
  case createqrticket = 17
  case createqrticketack = 18
  case qrticketstatusupdate = 19
  case scanqrticket = 20
  case confirmqrticket = 21
  case denyqrticket = 22
  case qrloginack = 23
  case logout = 24
  case logoutack = 25
  case listsessions = 26
  case listsessionsack = 27
  case logoutallsessions = 28
  case logoutallsessionsack = 29
  case setsessionttl = 30
  case setsessionttlack = 31

  public static var max: Protocol__Body { return .setsessionttlack }
  public static var min: Protocol__Body { return .none_ }
}


public enum Protocol__ErrorCode: Int8, FlatbuffersVectorInitializable, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case emailAlreadyExists = 1
  case invalidCode = 2
  case tooManyAttempts = 3
  case expiredCode = 4
  case rateLimitExceeded = 5
  case sessionNotFound = 6
  case deviceNotFound = 7
  case invalidRecipient = 8
  case identityAlreadyLinked = 9
  case oauthStateMismatch = 10
  case oauthExchangeFailed = 11
  case qrTicketNotFound = 12
  case qrTicketExpired = 13
  case sessionAlreadyRevoked = 14
  case invalidSessionTtl = 15

  public static var max: Protocol__ErrorCode { return .invalidSessionTtl }
  public static var min: Protocol__ErrorCode { return .unknown }
}


public enum Protocol__QRTicketStatus: Int8, FlatbuffersVectorInitializable, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case pending = 0
  case scanned = 1
  case confirmed = 2
  case denied = 3
  case expired = 4

  public static var max: Protocol__QRTicketStatus { return .expired }
  public static var min: Protocol__QRTicketStatus { return .pending }
}


public struct Protocol__Ping: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case timestamp = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var timestamp: Int64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPing(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(timestamp: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endPing(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPing(
    _ fbb: inout FlatBufferBuilder,
    timestamp: Int64 = 0
  ) -> Offset {
    let __start = Protocol__Ping.startPing(&fbb)
    Protocol__Ping.add(timestamp: timestamp, &fbb)
    return Protocol__Ping.endPing(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__Pong: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case timestamp = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var timestamp: Int64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPong(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(timestamp: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endPong(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPong(
    _ fbb: inout FlatBufferBuilder,
    timestamp: Int64 = 0
  ) -> Offset {
    let __start = Protocol__Pong.startPong(&fbb)
    Protocol__Pong.add(timestamp: timestamp, &fbb)
    return Protocol__Pong.endPong(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__NewSession: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case deviceId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var deviceId: UInt64 { let o = _accessor.offset(VTOFFSET.deviceId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startNewSession(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(deviceId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: deviceId, def: 0, at: VTOFFSET.deviceId.p) }
  public static func endNewSession(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createNewSession(
    _ fbb: inout FlatBufferBuilder,
    deviceId: UInt64 = 0
  ) -> Offset {
    let __start = Protocol__NewSession.startNewSession(&fbb)
    Protocol__NewSession.add(deviceId: deviceId, &fbb)
    return Protocol__NewSession.endNewSession(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.deviceId.p, fieldName: "deviceId", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct Protocol__ResumeSession: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public static func startResumeSession(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func endResumeSession(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createResumeSession(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__ResumeSession.startResumeSession(&fbb)
    Protocol__ResumeSession.add(sessionId: sessionId, &fbb)
    return Protocol__ResumeSession.endResumeSession(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__NewSessionAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    case currentSeq = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public var currentSeq: Int64 { let o = _accessor.offset(VTOFFSET.currentSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startNewSessionAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func add(currentSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentSeq, def: 0, at: VTOFFSET.currentSeq.p) }
  public static func endNewSessionAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createNewSessionAck(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset(),
    currentSeq: Int64 = 0
  ) -> Offset {
    let __start = Protocol__NewSessionAck.startNewSessionAck(&fbb)
    Protocol__NewSessionAck.add(sessionId: sessionId, &fbb)
    Protocol__NewSessionAck.add(currentSeq: currentSeq, &fbb)
    return Protocol__NewSessionAck.endNewSessionAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.currentSeq.p, fieldName: "currentSeq", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__ResumeSessionAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    case currentSeq = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public var currentSeq: Int64 { let o = _accessor.offset(VTOFFSET.currentSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startResumeSessionAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func add(currentSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentSeq, def: 0, at: VTOFFSET.currentSeq.p) }
  public static func endResumeSessionAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createResumeSessionAck(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset(),
    currentSeq: Int64 = 0
  ) -> Offset {
    let __start = Protocol__ResumeSessionAck.startResumeSessionAck(&fbb)
    Protocol__ResumeSessionAck.add(sessionId: sessionId, &fbb)
    Protocol__ResumeSessionAck.add(currentSeq: currentSeq, &fbb)
    return Protocol__ResumeSessionAck.endResumeSessionAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.currentSeq.p, fieldName: "currentSeq", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__RegisterAccount: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case email = 4
    case firstName = 6
    case lastName = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var email: String? { let o = _accessor.offset(VTOFFSET.email.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var emailSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.email.v) }
  public var firstName: String? { let o = _accessor.offset(VTOFFSET.firstName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var firstNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.firstName.v) }
  public var lastName: String? { let o = _accessor.offset(VTOFFSET.lastName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var lastNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.lastName.v) }
  public static func startRegisterAccount(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(email: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: email, at: VTOFFSET.email.p) }
  public static func add(firstName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: firstName, at: VTOFFSET.firstName.p) }
  public static func add(lastName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: lastName, at: VTOFFSET.lastName.p) }
  public static func endRegisterAccount(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createRegisterAccount(
    _ fbb: inout FlatBufferBuilder,
    emailOffset email: Offset = Offset(),
    firstNameOffset firstName: Offset = Offset(),
    lastNameOffset lastName: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__RegisterAccount.startRegisterAccount(&fbb)
    Protocol__RegisterAccount.add(email: email, &fbb)
    Protocol__RegisterAccount.add(firstName: firstName, &fbb)
    Protocol__RegisterAccount.add(lastName: lastName, &fbb)
    return Protocol__RegisterAccount.endRegisterAccount(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.email.p, fieldName: "email", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.firstName.p, fieldName: "firstName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.lastName.p, fieldName: "lastName", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__RegisterAccountAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case accountId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var accountId: UInt64 { let o = _accessor.offset(VTOFFSET.accountId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startRegisterAccountAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(accountId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accountId, def: 0, at: VTOFFSET.accountId.p) }
  public static func endRegisterAccountAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createRegisterAccountAck(
    _ fbb: inout FlatBufferBuilder,
    accountId: UInt64 = 0
  ) -> Offset {
    let __start = Protocol__RegisterAccountAck.startRegisterAccountAck(&fbb)
    Protocol__RegisterAccountAck.add(accountId: accountId, &fbb)
    return Protocol__RegisterAccountAck.endRegisterAccountAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.accountId.p, fieldName: "accountId", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct Protocol__ConfirmEmailCode: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case accountId = 4
    case code = 6
    case deviceFingerprint = 8
    case deviceName = 10
    case platform = 12
    case osVersion = 14
    case appVersion = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var accountId: UInt64 { let o = _accessor.offset(VTOFFSET.accountId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var code: String? { let o = _accessor.offset(VTOFFSET.code.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var codeSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.code.v) }
  public var deviceFingerprint: String? { let o = _accessor.offset(VTOFFSET.deviceFingerprint.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceFingerprintSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceFingerprint.v) }
  public var deviceName: String? { let o = _accessor.offset(VTOFFSET.deviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceName.v) }
  public var platform: String? { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public var osVersion: String? { let o = _accessor.offset(VTOFFSET.osVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var osVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.osVersion.v) }
  public var appVersion: String? { let o = _accessor.offset(VTOFFSET.appVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var appVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.appVersion.v) }
  public static func startConfirmEmailCode(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(accountId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accountId, def: 0, at: VTOFFSET.accountId.p) }
  public static func add(code: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: code, at: VTOFFSET.code.p) }
  public static func add(deviceFingerprint: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceFingerprint, at: VTOFFSET.deviceFingerprint.p) }
  public static func add(deviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceName, at: VTOFFSET.deviceName.p) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func add(osVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: osVersion, at: VTOFFSET.osVersion.p) }
  public static func add(appVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: appVersion, at: VTOFFSET.appVersion.p) }
  public static func endConfirmEmailCode(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createConfirmEmailCode(
    _ fbb: inout FlatBufferBuilder,
    accountId: UInt64 = 0,
    codeOffset code: Offset = Offset(),
    deviceFingerprintOffset deviceFingerprint: Offset = Offset(),
    deviceNameOffset deviceName: Offset = Offset(),
    platformOffset platform: Offset = Offset(),
    osVersionOffset osVersion: Offset = Offset(),
    appVersionOffset appVersion: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__ConfirmEmailCode.startConfirmEmailCode(&fbb)
    Protocol__ConfirmEmailCode.add(accountId: accountId, &fbb)
    Protocol__ConfirmEmailCode.add(code: code, &fbb)
    Protocol__ConfirmEmailCode.add(deviceFingerprint: deviceFingerprint, &fbb)
    Protocol__ConfirmEmailCode.add(deviceName: deviceName, &fbb)
    Protocol__ConfirmEmailCode.add(platform: platform, &fbb)
    Protocol__ConfirmEmailCode.add(osVersion: osVersion, &fbb)
    Protocol__ConfirmEmailCode.add(appVersion: appVersion, &fbb)
    return Protocol__ConfirmEmailCode.endConfirmEmailCode(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.accountId.p, fieldName: "accountId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.code.p, fieldName: "code", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceFingerprint.p, fieldName: "deviceFingerprint", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceName.p, fieldName: "deviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.osVersion.p, fieldName: "osVersion", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.appVersion.p, fieldName: "appVersion", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__ConfirmEmailCodeAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    case deviceId = 6
    case currentSeq = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public var deviceId: UInt64 { let o = _accessor.offset(VTOFFSET.deviceId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var currentSeq: Int64 { let o = _accessor.offset(VTOFFSET.currentSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startConfirmEmailCodeAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func add(deviceId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: deviceId, def: 0, at: VTOFFSET.deviceId.p) }
  public static func add(currentSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentSeq, def: 0, at: VTOFFSET.currentSeq.p) }
  public static func endConfirmEmailCodeAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createConfirmEmailCodeAck(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset(),
    deviceId: UInt64 = 0,
    currentSeq: Int64 = 0
  ) -> Offset {
    let __start = Protocol__ConfirmEmailCodeAck.startConfirmEmailCodeAck(&fbb)
    Protocol__ConfirmEmailCodeAck.add(sessionId: sessionId, &fbb)
    Protocol__ConfirmEmailCodeAck.add(deviceId: deviceId, &fbb)
    Protocol__ConfirmEmailCodeAck.add(currentSeq: currentSeq, &fbb)
    return Protocol__ConfirmEmailCodeAck.endConfirmEmailCodeAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceId.p, fieldName: "deviceId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.currentSeq.p, fieldName: "currentSeq", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__Error: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case code = 4
    case message = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var code: Protocol__ErrorCode { let o = _accessor.offset(VTOFFSET.code.v); return o == 0 ? .unknown : Protocol__ErrorCode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var message: String? { let o = _accessor.offset(VTOFFSET.message.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var messageSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.message.v) }
  public static func startError(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(code: Protocol__ErrorCode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: code.rawValue, def: 0, at: VTOFFSET.code.p) }
  public static func add(message: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: message, at: VTOFFSET.message.p) }
  public static func endError(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createError(
    _ fbb: inout FlatBufferBuilder,
    code: Protocol__ErrorCode = .unknown,
    messageOffset message: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__Error.startError(&fbb)
    Protocol__Error.add(code: code, &fbb)
    Protocol__Error.add(message: message, &fbb)
    return Protocol__Error.endError(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.code.p, fieldName: "code", required: false, type: Protocol__ErrorCode.self)
    try _v.visit(field: VTOFFSET.message.p, fieldName: "message", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__SendMessage: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case recipientAccountId = 4
    case clientMsgId = 6
    case text = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var recipientAccountId: UInt64 { let o = _accessor.offset(VTOFFSET.recipientAccountId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var clientMsgId: String? { let o = _accessor.offset(VTOFFSET.clientMsgId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var clientMsgIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.clientMsgId.v) }
  public var text: String? { let o = _accessor.offset(VTOFFSET.text.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var textSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.text.v) }
  public static func startSendMessage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(recipientAccountId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: recipientAccountId, def: 0, at: VTOFFSET.recipientAccountId.p) }
  public static func add(clientMsgId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: clientMsgId, at: VTOFFSET.clientMsgId.p) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endSendMessage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createSendMessage(
    _ fbb: inout FlatBufferBuilder,
    recipientAccountId: UInt64 = 0,
    clientMsgIdOffset clientMsgId: Offset = Offset(),
    textOffset text: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__SendMessage.startSendMessage(&fbb)
    Protocol__SendMessage.add(recipientAccountId: recipientAccountId, &fbb)
    Protocol__SendMessage.add(clientMsgId: clientMsgId, &fbb)
    Protocol__SendMessage.add(text: text, &fbb)
    return Protocol__SendMessage.endSendMessage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.recipientAccountId.p, fieldName: "recipientAccountId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.clientMsgId.p, fieldName: "clientMsgId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__SendMessageAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case clientMsgId = 4
    case serverMsgId = 6
    case createdAt = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var clientMsgId: String? { let o = _accessor.offset(VTOFFSET.clientMsgId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var clientMsgIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.clientMsgId.v) }
  public var serverMsgId: String? { let o = _accessor.offset(VTOFFSET.serverMsgId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var serverMsgIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.serverMsgId.v) }
  public var createdAt: Int64 { let o = _accessor.offset(VTOFFSET.createdAt.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startSendMessageAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(clientMsgId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: clientMsgId, at: VTOFFSET.clientMsgId.p) }
  public static func add(serverMsgId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: serverMsgId, at: VTOFFSET.serverMsgId.p) }
  public static func add(createdAt: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: createdAt, def: 0, at: VTOFFSET.createdAt.p) }
  public static func endSendMessageAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createSendMessageAck(
    _ fbb: inout FlatBufferBuilder,
    clientMsgIdOffset clientMsgId: Offset = Offset(),
    serverMsgIdOffset serverMsgId: Offset = Offset(),
    createdAt: Int64 = 0
  ) -> Offset {
    let __start = Protocol__SendMessageAck.startSendMessageAck(&fbb)
    Protocol__SendMessageAck.add(clientMsgId: clientMsgId, &fbb)
    Protocol__SendMessageAck.add(serverMsgId: serverMsgId, &fbb)
    Protocol__SendMessageAck.add(createdAt: createdAt, &fbb)
    return Protocol__SendMessageAck.endSendMessageAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.clientMsgId.p, fieldName: "clientMsgId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.serverMsgId.p, fieldName: "serverMsgId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.createdAt.p, fieldName: "createdAt", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__MessageUpdate: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case serverMsgId = 4
    case senderAccountId = 6
    case text = 8
    case createdAt = 10
    case seqNo = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var serverMsgId: String? { let o = _accessor.offset(VTOFFSET.serverMsgId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var serverMsgIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.serverMsgId.v) }
  public var senderAccountId: UInt64 { let o = _accessor.offset(VTOFFSET.senderAccountId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var text: String? { let o = _accessor.offset(VTOFFSET.text.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var textSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.text.v) }
  public var createdAt: Int64 { let o = _accessor.offset(VTOFFSET.createdAt.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var seqNo: Int64 { let o = _accessor.offset(VTOFFSET.seqNo.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startMessageUpdate(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(serverMsgId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: serverMsgId, at: VTOFFSET.serverMsgId.p) }
  public static func add(senderAccountId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: senderAccountId, def: 0, at: VTOFFSET.senderAccountId.p) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func add(createdAt: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: createdAt, def: 0, at: VTOFFSET.createdAt.p) }
  public static func add(seqNo: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: seqNo, def: 0, at: VTOFFSET.seqNo.p) }
  public static func endMessageUpdate(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createMessageUpdate(
    _ fbb: inout FlatBufferBuilder,
    serverMsgIdOffset serverMsgId: Offset = Offset(),
    senderAccountId: UInt64 = 0,
    textOffset text: Offset = Offset(),
    createdAt: Int64 = 0,
    seqNo: Int64 = 0
  ) -> Offset {
    let __start = Protocol__MessageUpdate.startMessageUpdate(&fbb)
    Protocol__MessageUpdate.add(serverMsgId: serverMsgId, &fbb)
    Protocol__MessageUpdate.add(senderAccountId: senderAccountId, &fbb)
    Protocol__MessageUpdate.add(text: text, &fbb)
    Protocol__MessageUpdate.add(createdAt: createdAt, &fbb)
    Protocol__MessageUpdate.add(seqNo: seqNo, &fbb)
    return Protocol__MessageUpdate.endMessageUpdate(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.serverMsgId.p, fieldName: "serverMsgId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.senderAccountId.p, fieldName: "senderAccountId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.createdAt.p, fieldName: "createdAt", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.seqNo.p, fieldName: "seqNo", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__GetDifference: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sinceSeq = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sinceSeq: Int64 { let o = _accessor.offset(VTOFFSET.sinceSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startGetDifference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(sinceSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: sinceSeq, def: 0, at: VTOFFSET.sinceSeq.p) }
  public static func endGetDifference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createGetDifference(
    _ fbb: inout FlatBufferBuilder,
    sinceSeq: Int64 = 0
  ) -> Offset {
    let __start = Protocol__GetDifference.startGetDifference(&fbb)
    Protocol__GetDifference.add(sinceSeq: sinceSeq, &fbb)
    return Protocol__GetDifference.endGetDifference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sinceSeq.p, fieldName: "sinceSeq", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__DifferenceAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case updates = 4
    case currentSeq = 6
    case hasMore = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var updates: FlatbufferVector<Protocol__MessageUpdate> { return _accessor.vector(at: VTOFFSET.updates.v, byteSize: 4) }
  public var currentSeq: Int64 { let o = _accessor.offset(VTOFFSET.currentSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasMore: Bool { let o = _accessor.offset(VTOFFSET.hasMore.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startDifferenceAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func addVectorOf(updates: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: updates, at: VTOFFSET.updates.p) }
  public static func add(currentSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentSeq, def: 0, at: VTOFFSET.currentSeq.p) }
  public static func add(hasMore: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasMore, def: false,
   at: VTOFFSET.hasMore.p) }
  public static func endDifferenceAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createDifferenceAck(
    _ fbb: inout FlatBufferBuilder,
    updatesVectorOffset updates: Offset = Offset(),
    currentSeq: Int64 = 0,
    hasMore: Bool = false
  ) -> Offset {
    let __start = Protocol__DifferenceAck.startDifferenceAck(&fbb)
    Protocol__DifferenceAck.addVectorOf(updates: updates, &fbb)
    Protocol__DifferenceAck.add(currentSeq: currentSeq, &fbb)
    Protocol__DifferenceAck.add(hasMore: hasMore, &fbb)
    return Protocol__DifferenceAck.endDifferenceAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.updates.p, fieldName: "updates", required: false, type: ForwardOffset<Vector<ForwardOffset<Protocol__MessageUpdate>, Protocol__MessageUpdate>>.self)
    try _v.visit(field: VTOFFSET.currentSeq.p, fieldName: "currentSeq", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.hasMore.p, fieldName: "hasMore", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct Protocol__CreateQRTicket: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case deviceName = 4
    case platform = 6
    case osVersion = 8
    case appVersion = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var deviceName: String? { let o = _accessor.offset(VTOFFSET.deviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceName.v) }
  public var platform: String? { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public var osVersion: String? { let o = _accessor.offset(VTOFFSET.osVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var osVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.osVersion.v) }
  public var appVersion: String? { let o = _accessor.offset(VTOFFSET.appVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var appVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.appVersion.v) }
  public static func startCreateQRTicket(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(deviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceName, at: VTOFFSET.deviceName.p) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func add(osVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: osVersion, at: VTOFFSET.osVersion.p) }
  public static func add(appVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: appVersion, at: VTOFFSET.appVersion.p) }
  public static func endCreateQRTicket(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCreateQRTicket(
    _ fbb: inout FlatBufferBuilder,
    deviceNameOffset deviceName: Offset = Offset(),
    platformOffset platform: Offset = Offset(),
    osVersionOffset osVersion: Offset = Offset(),
    appVersionOffset appVersion: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__CreateQRTicket.startCreateQRTicket(&fbb)
    Protocol__CreateQRTicket.add(deviceName: deviceName, &fbb)
    Protocol__CreateQRTicket.add(platform: platform, &fbb)
    Protocol__CreateQRTicket.add(osVersion: osVersion, &fbb)
    Protocol__CreateQRTicket.add(appVersion: appVersion, &fbb)
    return Protocol__CreateQRTicket.endCreateQRTicket(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.deviceName.p, fieldName: "deviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.osVersion.p, fieldName: "osVersion", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.appVersion.p, fieldName: "appVersion", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__CreateQRTicketAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ticketId = 4
    case expiresAt = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ticketId: String? { let o = _accessor.offset(VTOFFSET.ticketId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ticketIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ticketId.v) }
  public var expiresAt: Int64 { let o = _accessor.offset(VTOFFSET.expiresAt.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startCreateQRTicketAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(ticketId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ticketId, at: VTOFFSET.ticketId.p) }
  public static func add(expiresAt: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: expiresAt, def: 0, at: VTOFFSET.expiresAt.p) }
  public static func endCreateQRTicketAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCreateQRTicketAck(
    _ fbb: inout FlatBufferBuilder,
    ticketIdOffset ticketId: Offset = Offset(),
    expiresAt: Int64 = 0
  ) -> Offset {
    let __start = Protocol__CreateQRTicketAck.startCreateQRTicketAck(&fbb)
    Protocol__CreateQRTicketAck.add(ticketId: ticketId, &fbb)
    Protocol__CreateQRTicketAck.add(expiresAt: expiresAt, &fbb)
    return Protocol__CreateQRTicketAck.endCreateQRTicketAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ticketId.p, fieldName: "ticketId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.expiresAt.p, fieldName: "expiresAt", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__QRTicketStatusUpdate: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ticketId = 4
    case status = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ticketId: String? { let o = _accessor.offset(VTOFFSET.ticketId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ticketIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ticketId.v) }
  public var status: Protocol__QRTicketStatus { let o = _accessor.offset(VTOFFSET.status.v); return o == 0 ? .pending : Protocol__QRTicketStatus(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .pending }
  public static func startQRTicketStatusUpdate(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(ticketId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ticketId, at: VTOFFSET.ticketId.p) }
  public static func add(status: Protocol__QRTicketStatus, _ fbb: inout FlatBufferBuilder) { fbb.add(element: status.rawValue, def: 0, at: VTOFFSET.status.p) }
  public static func endQRTicketStatusUpdate(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createQRTicketStatusUpdate(
    _ fbb: inout FlatBufferBuilder,
    ticketIdOffset ticketId: Offset = Offset(),
    status: Protocol__QRTicketStatus = .pending
  ) -> Offset {
    let __start = Protocol__QRTicketStatusUpdate.startQRTicketStatusUpdate(&fbb)
    Protocol__QRTicketStatusUpdate.add(ticketId: ticketId, &fbb)
    Protocol__QRTicketStatusUpdate.add(status: status, &fbb)
    return Protocol__QRTicketStatusUpdate.endQRTicketStatusUpdate(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ticketId.p, fieldName: "ticketId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.status.p, fieldName: "status", required: false, type: Protocol__QRTicketStatus.self)
    _v.finish()
  }
}

public struct Protocol__ScanQRTicket: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ticketId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ticketId: String? { let o = _accessor.offset(VTOFFSET.ticketId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ticketIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ticketId.v) }
  public static func startScanQRTicket(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ticketId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ticketId, at: VTOFFSET.ticketId.p) }
  public static func endScanQRTicket(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createScanQRTicket(
    _ fbb: inout FlatBufferBuilder,
    ticketIdOffset ticketId: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__ScanQRTicket.startScanQRTicket(&fbb)
    Protocol__ScanQRTicket.add(ticketId: ticketId, &fbb)
    return Protocol__ScanQRTicket.endScanQRTicket(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ticketId.p, fieldName: "ticketId", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__ConfirmQRTicket: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ticketId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ticketId: String? { let o = _accessor.offset(VTOFFSET.ticketId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ticketIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ticketId.v) }
  public static func startConfirmQRTicket(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ticketId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ticketId, at: VTOFFSET.ticketId.p) }
  public static func endConfirmQRTicket(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createConfirmQRTicket(
    _ fbb: inout FlatBufferBuilder,
    ticketIdOffset ticketId: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__ConfirmQRTicket.startConfirmQRTicket(&fbb)
    Protocol__ConfirmQRTicket.add(ticketId: ticketId, &fbb)
    return Protocol__ConfirmQRTicket.endConfirmQRTicket(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ticketId.p, fieldName: "ticketId", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__DenyQRTicket: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ticketId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ticketId: String? { let o = _accessor.offset(VTOFFSET.ticketId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ticketIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ticketId.v) }
  public static func startDenyQRTicket(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ticketId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ticketId, at: VTOFFSET.ticketId.p) }
  public static func endDenyQRTicket(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createDenyQRTicket(
    _ fbb: inout FlatBufferBuilder,
    ticketIdOffset ticketId: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__DenyQRTicket.startDenyQRTicket(&fbb)
    Protocol__DenyQRTicket.add(ticketId: ticketId, &fbb)
    return Protocol__DenyQRTicket.endDenyQRTicket(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ticketId.p, fieldName: "ticketId", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Protocol__QRLoginAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    case deviceId = 6
    case accountId = 8
    case currentSeq = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public var deviceId: UInt64 { let o = _accessor.offset(VTOFFSET.deviceId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var accountId: UInt64 { let o = _accessor.offset(VTOFFSET.accountId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var currentSeq: Int64 { let o = _accessor.offset(VTOFFSET.currentSeq.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startQRLoginAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func add(deviceId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: deviceId, def: 0, at: VTOFFSET.deviceId.p) }
  public static func add(accountId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accountId, def: 0, at: VTOFFSET.accountId.p) }
  public static func add(currentSeq: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentSeq, def: 0, at: VTOFFSET.currentSeq.p) }
  public static func endQRLoginAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createQRLoginAck(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset(),
    deviceId: UInt64 = 0,
    accountId: UInt64 = 0,
    currentSeq: Int64 = 0
  ) -> Offset {
    let __start = Protocol__QRLoginAck.startQRLoginAck(&fbb)
    Protocol__QRLoginAck.add(sessionId: sessionId, &fbb)
    Protocol__QRLoginAck.add(deviceId: deviceId, &fbb)
    Protocol__QRLoginAck.add(accountId: accountId, &fbb)
    Protocol__QRLoginAck.add(currentSeq: currentSeq, &fbb)
    return Protocol__QRLoginAck.endQRLoginAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceId.p, fieldName: "deviceId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.accountId.p, fieldName: "accountId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.currentSeq.p, fieldName: "currentSeq", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__Logout: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startLogout(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endLogout(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct Protocol__LogoutAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startLogoutAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endLogoutAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct Protocol__ListSessions: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startListSessions(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endListSessions(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct Protocol__SessionInfo: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessionId = 4
    case deviceId = 6
    case deviceName = 8
    case platform = 10
    case osVersion = 12
    case isCurrent = 14
    case createdAt = 16
    case lastActiveAt = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessionId: String? { let o = _accessor.offset(VTOFFSET.sessionId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sessionIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sessionId.v) }
  public var deviceId: UInt64 { let o = _accessor.offset(VTOFFSET.deviceId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var deviceName: String? { let o = _accessor.offset(VTOFFSET.deviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceName.v) }
  public var platform: String? { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public var osVersion: String? { let o = _accessor.offset(VTOFFSET.osVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var osVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.osVersion.v) }
  public var isCurrent: Bool { let o = _accessor.offset(VTOFFSET.isCurrent.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var createdAt: Int64 { let o = _accessor.offset(VTOFFSET.createdAt.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var lastActiveAt: Int64 { let o = _accessor.offset(VTOFFSET.lastActiveAt.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startSessionInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func add(sessionId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessionId, at: VTOFFSET.sessionId.p) }
  public static func add(deviceId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: deviceId, def: 0, at: VTOFFSET.deviceId.p) }
  public static func add(deviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceName, at: VTOFFSET.deviceName.p) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func add(osVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: osVersion, at: VTOFFSET.osVersion.p) }
  public static func add(isCurrent: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isCurrent, def: false,
   at: VTOFFSET.isCurrent.p) }
  public static func add(createdAt: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: createdAt, def: 0, at: VTOFFSET.createdAt.p) }
  public static func add(lastActiveAt: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lastActiveAt, def: 0, at: VTOFFSET.lastActiveAt.p) }
  public static func endSessionInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createSessionInfo(
    _ fbb: inout FlatBufferBuilder,
    sessionIdOffset sessionId: Offset = Offset(),
    deviceId: UInt64 = 0,
    deviceNameOffset deviceName: Offset = Offset(),
    platformOffset platform: Offset = Offset(),
    osVersionOffset osVersion: Offset = Offset(),
    isCurrent: Bool = false,
    createdAt: Int64 = 0,
    lastActiveAt: Int64 = 0
  ) -> Offset {
    let __start = Protocol__SessionInfo.startSessionInfo(&fbb)
    Protocol__SessionInfo.add(sessionId: sessionId, &fbb)
    Protocol__SessionInfo.add(deviceId: deviceId, &fbb)
    Protocol__SessionInfo.add(deviceName: deviceName, &fbb)
    Protocol__SessionInfo.add(platform: platform, &fbb)
    Protocol__SessionInfo.add(osVersion: osVersion, &fbb)
    Protocol__SessionInfo.add(isCurrent: isCurrent, &fbb)
    Protocol__SessionInfo.add(createdAt: createdAt, &fbb)
    Protocol__SessionInfo.add(lastActiveAt: lastActiveAt, &fbb)
    return Protocol__SessionInfo.endSessionInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessionId.p, fieldName: "sessionId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceId.p, fieldName: "deviceId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.deviceName.p, fieldName: "deviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.osVersion.p, fieldName: "osVersion", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.isCurrent.p, fieldName: "isCurrent", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.createdAt.p, fieldName: "createdAt", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.lastActiveAt.p, fieldName: "lastActiveAt", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct Protocol__ListSessionsAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessions = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessions: FlatbufferVector<Protocol__SessionInfo> { return _accessor.vector(at: VTOFFSET.sessions.v, byteSize: 4) }
  public static func startListSessionsAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func addVectorOf(sessions: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessions, at: VTOFFSET.sessions.p) }
  public static func endListSessionsAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createListSessionsAck(
    _ fbb: inout FlatBufferBuilder,
    sessionsVectorOffset sessions: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__ListSessionsAck.startListSessionsAck(&fbb)
    Protocol__ListSessionsAck.addVectorOf(sessions: sessions, &fbb)
    return Protocol__ListSessionsAck.endListSessionsAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessions.p, fieldName: "sessions", required: false, type: ForwardOffset<Vector<ForwardOffset<Protocol__SessionInfo>, Protocol__SessionInfo>>.self)
    _v.finish()
  }
}

public struct Protocol__LogoutAllSessions: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case exceptCurrent = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var exceptCurrent: Bool { let o = _accessor.offset(VTOFFSET.exceptCurrent.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startLogoutAllSessions(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(exceptCurrent: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: exceptCurrent, def: false,
   at: VTOFFSET.exceptCurrent.p) }
  public static func endLogoutAllSessions(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createLogoutAllSessions(
    _ fbb: inout FlatBufferBuilder,
    exceptCurrent: Bool = false
  ) -> Offset {
    let __start = Protocol__LogoutAllSessions.startLogoutAllSessions(&fbb)
    Protocol__LogoutAllSessions.add(exceptCurrent: exceptCurrent, &fbb)
    return Protocol__LogoutAllSessions.endLogoutAllSessions(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.exceptCurrent.p, fieldName: "exceptCurrent", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct Protocol__LogoutAllSessionsAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case revokedCount = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var revokedCount: Int32 { let o = _accessor.offset(VTOFFSET.revokedCount.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startLogoutAllSessionsAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(revokedCount: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: revokedCount, def: 0, at: VTOFFSET.revokedCount.p) }
  public static func endLogoutAllSessionsAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createLogoutAllSessionsAck(
    _ fbb: inout FlatBufferBuilder,
    revokedCount: Int32 = 0
  ) -> Offset {
    let __start = Protocol__LogoutAllSessionsAck.startLogoutAllSessionsAck(&fbb)
    Protocol__LogoutAllSessionsAck.add(revokedCount: revokedCount, &fbb)
    return Protocol__LogoutAllSessionsAck.endLogoutAllSessionsAck(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.revokedCount.p, fieldName: "revokedCount", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct Protocol__SetSessionTTL: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case hasMonths = 4
    case months = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasMonths: Bool { let o = _accessor.offset(VTOFFSET.hasMonths.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var months: Int32 { let o = _accessor.offset(VTOFFSET.months.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startSetSessionTTL(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(hasMonths: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasMonths, def: false,
   at: VTOFFSET.hasMonths.p) }
  public static func add(months: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: months, def: 0, at: VTOFFSET.months.p) }
  public static func endSetSessionTTL(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createSetSessionTTL(
    _ fbb: inout FlatBufferBuilder,
    hasMonths: Bool = false,
    months: Int32 = 0
  ) -> Offset {
    let __start = Protocol__SetSessionTTL.startSetSessionTTL(&fbb)
    Protocol__SetSessionTTL.add(hasMonths: hasMonths, &fbb)
    Protocol__SetSessionTTL.add(months: months, &fbb)
    return Protocol__SetSessionTTL.endSetSessionTTL(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.hasMonths.p, fieldName: "hasMonths", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.months.p, fieldName: "months", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct Protocol__SetSessionTTLAck: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startSetSessionTTLAck(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endSetSessionTTLAck(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct Protocol__Envelope: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case requestId = 4
    case bodyType = 6
    case body = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var requestId: UInt64 { let o = _accessor.offset(VTOFFSET.requestId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var bodyType: Protocol__Body { let o = _accessor.offset(VTOFFSET.bodyType.v); return o == 0 ? .none_ : Protocol__Body(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func body<T: FlatbuffersInitializable>(type: T.Type) -> T? { let o = _accessor.offset(VTOFFSET.body.v); return o == 0 ? nil : _accessor.union(o) }
  public static func startEnvelope(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(requestId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: requestId, def: 0, at: VTOFFSET.requestId.p) }
  public static func add(bodyType: Protocol__Body, _ fbb: inout FlatBufferBuilder) { fbb.add(element: bodyType.rawValue, def: 0, at: VTOFFSET.bodyType.p) }
  public static func add(body: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: body, at: VTOFFSET.body.p) }
  public static func endEnvelope(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createEnvelope(
    _ fbb: inout FlatBufferBuilder,
    requestId: UInt64 = 0,
    bodyType: Protocol__Body = .none_,
    bodyOffset body: Offset = Offset()
  ) -> Offset {
    let __start = Protocol__Envelope.startEnvelope(&fbb)
    Protocol__Envelope.add(requestId: requestId, &fbb)
    Protocol__Envelope.add(bodyType: bodyType, &fbb)
    Protocol__Envelope.add(body: body, &fbb)
    return Protocol__Envelope.endEnvelope(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.requestId.p, fieldName: "requestId", required: false, type: UInt64.self)
    try _v.visit(unionKey: VTOFFSET.bodyType.p, unionField: VTOFFSET.body.p, unionKeyName: "bodyType", fieldName: "body", required: false, completion: { (verifier, key: Protocol__Body, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .ping:
        try ForwardOffset<Protocol__Ping>.verify(&verifier, at: pos, of: Protocol__Ping.self)
      case .pong:
        try ForwardOffset<Protocol__Pong>.verify(&verifier, at: pos, of: Protocol__Pong.self)
      case .newsession:
        try ForwardOffset<Protocol__NewSession>.verify(&verifier, at: pos, of: Protocol__NewSession.self)
      case .resumesession:
        try ForwardOffset<Protocol__ResumeSession>.verify(&verifier, at: pos, of: Protocol__ResumeSession.self)
      case .registeraccount:
        try ForwardOffset<Protocol__RegisterAccount>.verify(&verifier, at: pos, of: Protocol__RegisterAccount.self)
      case .registeraccountack:
        try ForwardOffset<Protocol__RegisterAccountAck>.verify(&verifier, at: pos, of: Protocol__RegisterAccountAck.self)
      case .confirmemailcode:
        try ForwardOffset<Protocol__ConfirmEmailCode>.verify(&verifier, at: pos, of: Protocol__ConfirmEmailCode.self)
      case .confirmemailcodeack:
        try ForwardOffset<Protocol__ConfirmEmailCodeAck>.verify(&verifier, at: pos, of: Protocol__ConfirmEmailCodeAck.self)
      case .error:
        try ForwardOffset<Protocol__Error>.verify(&verifier, at: pos, of: Protocol__Error.self)
      case .newsessionack:
        try ForwardOffset<Protocol__NewSessionAck>.verify(&verifier, at: pos, of: Protocol__NewSessionAck.self)
      case .resumesessionack:
        try ForwardOffset<Protocol__ResumeSessionAck>.verify(&verifier, at: pos, of: Protocol__ResumeSessionAck.self)
      case .sendmessage:
        try ForwardOffset<Protocol__SendMessage>.verify(&verifier, at: pos, of: Protocol__SendMessage.self)
      case .sendmessageack:
        try ForwardOffset<Protocol__SendMessageAck>.verify(&verifier, at: pos, of: Protocol__SendMessageAck.self)
      case .messageupdate:
        try ForwardOffset<Protocol__MessageUpdate>.verify(&verifier, at: pos, of: Protocol__MessageUpdate.self)
      case .getdifference:
        try ForwardOffset<Protocol__GetDifference>.verify(&verifier, at: pos, of: Protocol__GetDifference.self)
      case .differenceack:
        try ForwardOffset<Protocol__DifferenceAck>.verify(&verifier, at: pos, of: Protocol__DifferenceAck.self)
      case .createqrticket:
        try ForwardOffset<Protocol__CreateQRTicket>.verify(&verifier, at: pos, of: Protocol__CreateQRTicket.self)
      case .createqrticketack:
        try ForwardOffset<Protocol__CreateQRTicketAck>.verify(&verifier, at: pos, of: Protocol__CreateQRTicketAck.self)
      case .qrticketstatusupdate:
        try ForwardOffset<Protocol__QRTicketStatusUpdate>.verify(&verifier, at: pos, of: Protocol__QRTicketStatusUpdate.self)
      case .scanqrticket:
        try ForwardOffset<Protocol__ScanQRTicket>.verify(&verifier, at: pos, of: Protocol__ScanQRTicket.self)
      case .confirmqrticket:
        try ForwardOffset<Protocol__ConfirmQRTicket>.verify(&verifier, at: pos, of: Protocol__ConfirmQRTicket.self)
      case .denyqrticket:
        try ForwardOffset<Protocol__DenyQRTicket>.verify(&verifier, at: pos, of: Protocol__DenyQRTicket.self)
      case .qrloginack:
        try ForwardOffset<Protocol__QRLoginAck>.verify(&verifier, at: pos, of: Protocol__QRLoginAck.self)
      case .logout:
        try ForwardOffset<Protocol__Logout>.verify(&verifier, at: pos, of: Protocol__Logout.self)
      case .logoutack:
        try ForwardOffset<Protocol__LogoutAck>.verify(&verifier, at: pos, of: Protocol__LogoutAck.self)
      case .listsessions:
        try ForwardOffset<Protocol__ListSessions>.verify(&verifier, at: pos, of: Protocol__ListSessions.self)
      case .listsessionsack:
        try ForwardOffset<Protocol__ListSessionsAck>.verify(&verifier, at: pos, of: Protocol__ListSessionsAck.self)
      case .logoutallsessions:
        try ForwardOffset<Protocol__LogoutAllSessions>.verify(&verifier, at: pos, of: Protocol__LogoutAllSessions.self)
      case .logoutallsessionsack:
        try ForwardOffset<Protocol__LogoutAllSessionsAck>.verify(&verifier, at: pos, of: Protocol__LogoutAllSessionsAck.self)
      case .setsessionttl:
        try ForwardOffset<Protocol__SetSessionTTL>.verify(&verifier, at: pos, of: Protocol__SetSessionTTL.self)
      case .setsessionttlack:
        try ForwardOffset<Protocol__SetSessionTTLAck>.verify(&verifier, at: pos, of: Protocol__SetSessionTTLAck.self)
      }
    })
    _v.finish()
  }
}

