// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public enum authv1_Platform: Int8, FlatbuffersVectorInitializable, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case web = 1
  case ios = 2
  case android = 3
  case macos = 4

  public static var max: authv1_Platform { return .macos }
  public static var min: authv1_Platform { return .unknown }
}


public struct authv1_ClientContext: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case platform = 4
    case os = 6
    case deviceName = 8
    case userAgent = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var platform: authv1_Platform { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? .unknown : authv1_Platform(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var os: String? { let o = _accessor.offset(VTOFFSET.os.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var osSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.os.v) }
  public var deviceName: String? { let o = _accessor.offset(VTOFFSET.deviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceName.v) }
  public var userAgent: String? { let o = _accessor.offset(VTOFFSET.userAgent.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var userAgentSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.userAgent.v) }
  public static func startClientContext(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(platform: authv1_Platform, _ fbb: inout FlatBufferBuilder) { fbb.add(element: platform.rawValue, def: 0, at: VTOFFSET.platform.p) }
  public static func add(os: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: os, at: VTOFFSET.os.p) }
  public static func add(deviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceName, at: VTOFFSET.deviceName.p) }
  public static func add(userAgent: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: userAgent, at: VTOFFSET.userAgent.p) }
  public static func endClientContext(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createClientContext(
    _ fbb: inout FlatBufferBuilder,
    platform: authv1_Platform = .unknown,
    osOffset os: Offset = Offset(),
    deviceNameOffset deviceName: Offset = Offset(),
    userAgentOffset userAgent: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ClientContext.startClientContext(&fbb)
    authv1_ClientContext.add(platform: platform, &fbb)
    authv1_ClientContext.add(os: os, &fbb)
    authv1_ClientContext.add(deviceName: deviceName, &fbb)
    authv1_ClientContext.add(userAgent: userAgent, &fbb)
    return authv1_ClientContext.endClientContext(&fbb, start: __start)
  }

  public func unpack() -> authv1_ClientContextT {
    return authv1_ClientContextT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ClientContextT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ClientContextT) -> Offset {
    let __os: Offset
    if let s = obj.os {
      __os = builder.create(string: s)
    } else {
      __os = Offset()
    }

    let __deviceName: Offset
    if let s = obj.deviceName {
      __deviceName = builder.create(string: s)
    } else {
      __deviceName = Offset()
    }

    let __userAgent: Offset
    if let s = obj.userAgent {
      __userAgent = builder.create(string: s)
    } else {
      __userAgent = Offset()
    }

    let __root = authv1_ClientContext.startClientContext(&builder)
    authv1_ClientContext.add(platform: obj.platform, &builder)
    authv1_ClientContext.add(os: __os, &builder)
    authv1_ClientContext.add(deviceName: __deviceName, &builder)
    authv1_ClientContext.add(userAgent: __userAgent, &builder)
    return authv1_ClientContext.endClientContext(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: authv1_Platform.self)
    try _v.visit(field: VTOFFSET.os.p, fieldName: "os", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceName.p, fieldName: "deviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.userAgent.p, fieldName: "userAgent", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_ClientContextT: NativeObject {

  public var platform: authv1_Platform
  public var os: String?
  public var deviceName: String?
  public var userAgent: String?

  public init(_ _t: borrowing authv1_ClientContext) {
    platform = _t.platform
    os = _t.os
    deviceName = _t.deviceName
    userAgent = _t.userAgent
  }

  public init() {
    platform = .unknown
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ClientContext.self) }

}
