// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public struct authv1_LoginByGithubRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case code = 4
    case clientCtx = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var code: String? { let o = _accessor.offset(VTOFFSET.code.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var codeSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.code.v) }
  public var clientCtx: authv1_ClientContext? { let o = _accessor.offset(VTOFFSET.clientCtx.v); return o == 0 ? nil : authv1_ClientContext(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startLoginByGithubRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(code: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: code, at: VTOFFSET.code.p) }
  public static func add(clientCtx: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: clientCtx, at: VTOFFSET.clientCtx.p) }
  public static func endLoginByGithubRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createLoginByGithubRequest(
    _ fbb: inout FlatBufferBuilder,
    codeOffset code: Offset = Offset(),
    clientCtxOffset clientCtx: Offset = Offset()
  ) -> Offset {
    let __start = authv1_LoginByGithubRequest.startLoginByGithubRequest(&fbb)
    authv1_LoginByGithubRequest.add(code: code, &fbb)
    authv1_LoginByGithubRequest.add(clientCtx: clientCtx, &fbb)
    return authv1_LoginByGithubRequest.endLoginByGithubRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_LoginByGithubRequestT {
    return authv1_LoginByGithubRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_LoginByGithubRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_LoginByGithubRequestT) -> Offset {
    let __code: Offset
    if let s = obj.code {
      __code = builder.create(string: s)
    } else {
      __code = Offset()
    }

    let __clientCtx = authv1_ClientContext.pack(&builder, obj: &obj.clientCtx)
    let __root = authv1_LoginByGithubRequest.startLoginByGithubRequest(&builder)
    authv1_LoginByGithubRequest.add(code: __code, &builder)
    authv1_LoginByGithubRequest.add(clientCtx: __clientCtx, &builder)
    return authv1_LoginByGithubRequest.endLoginByGithubRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.code.p, fieldName: "code", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.clientCtx.p, fieldName: "clientCtx", required: false, type: ForwardOffset<authv1_ClientContext>.self)
    _v.finish()
  }
}

public class authv1_LoginByGithubRequestT: NativeObject {

  public var code: String?
  public var clientCtx: authv1_ClientContextT?

  public init(_ _t: borrowing authv1_LoginByGithubRequest) {
    code = _t.code
    clientCtx = _t.clientCtx?.unpack()
  }

  public init() {
    clientCtx = authv1_ClientContextT()
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_LoginByGithubRequest.self) }

}
public struct authv1_LoginByGithubResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    case userId = 6
    case resumeSecret = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var userId: Int32 { let o = _accessor.offset(VTOFFSET.userId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var resumeSecret: String? { let o = _accessor.offset(VTOFFSET.resumeSecret.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var resumeSecretSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.resumeSecret.v) }
  public static func startLoginByGithubResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func add(userId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: userId, def: 0, at: VTOFFSET.userId.p) }
  public static func add(resumeSecret: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resumeSecret, at: VTOFFSET.resumeSecret.p) }
  public static func endLoginByGithubResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createLoginByGithubResponse(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0,
    userId: Int32 = 0,
    resumeSecretOffset resumeSecret: Offset = Offset()
  ) -> Offset {
    let __start = authv1_LoginByGithubResponse.startLoginByGithubResponse(&fbb)
    authv1_LoginByGithubResponse.add(authKeyId: authKeyId, &fbb)
    authv1_LoginByGithubResponse.add(userId: userId, &fbb)
    authv1_LoginByGithubResponse.add(resumeSecret: resumeSecret, &fbb)
    return authv1_LoginByGithubResponse.endLoginByGithubResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_LoginByGithubResponseT {
    return authv1_LoginByGithubResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_LoginByGithubResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_LoginByGithubResponseT) -> Offset {
    let __resumeSecret: Offset
    if let s = obj.resumeSecret {
      __resumeSecret = builder.create(string: s)
    } else {
      __resumeSecret = Offset()
    }

    let __root = authv1_LoginByGithubResponse.startLoginByGithubResponse(&builder)
    authv1_LoginByGithubResponse.add(authKeyId: obj.authKeyId, &builder)
    authv1_LoginByGithubResponse.add(userId: obj.userId, &builder)
    authv1_LoginByGithubResponse.add(resumeSecret: __resumeSecret, &builder)
    return authv1_LoginByGithubResponse.endLoginByGithubResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.userId.p, fieldName: "userId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.resumeSecret.p, fieldName: "resumeSecret", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_LoginByGithubResponseT: NativeObject {

  public var authKeyId: UInt64
  public var userId: Int32
  public var resumeSecret: String?

  public init(_ _t: borrowing authv1_LoginByGithubResponse) {
    authKeyId = _t.authKeyId
    userId = _t.userId
    resumeSecret = _t.resumeSecret
  }

  public init() {
    authKeyId = 0
    userId = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_LoginByGithubResponse.self) }

}
