// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public enum authv1_QRLoginFailReason: Int8, FlatbuffersVectorInitializable, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case tokenexpired = 1
  case alreadyused = 2
  case notfound = 3

  public static var max: authv1_QRLoginFailReason { return .notfound }
  public static var min: authv1_QRLoginFailReason { return .unknown }
}


public enum authv1_QRLoginEventPayload: UInt8, FlatbuffersVectorInitializable, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case qrloginconfirmed = 1
  case qrloginexpiredorrejected = 2

  public static var max: authv1_QRLoginEventPayload { return .qrloginexpiredorrejected }
  public static var min: authv1_QRLoginEventPayload { return .none_ }
}


public struct authv1_QRLoginEventPayloadUnion {
  public var type: authv1_QRLoginEventPayload
  public var value: NativeObject?
  public init(_ v: NativeObject?, type: authv1_QRLoginEventPayload) {
    self.type = type
    self.value = v
  }
  public func pack(builder: inout FlatBufferBuilder) -> Offset {
    switch type {
    case .qrloginconfirmed:
      var __obj = value as? authv1_QRLoginConfirmedT
      return authv1_QRLoginConfirmed.pack(&builder, obj: &__obj)
    case .qrloginexpiredorrejected:
      var __obj = value as? authv1_QRLoginExpiredOrRejectedT
      return authv1_QRLoginExpiredOrRejected.pack(&builder, obj: &__obj)
    default: return Offset()
    }
  }
}
public struct authv1_GenerateQRLoginRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case clientCtx = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var clientCtx: authv1_ClientContext? { let o = _accessor.offset(VTOFFSET.clientCtx.v); return o == 0 ? nil : authv1_ClientContext(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startGenerateQRLoginRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(clientCtx: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: clientCtx, at: VTOFFSET.clientCtx.p) }
  public static func endGenerateQRLoginRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createGenerateQRLoginRequest(
    _ fbb: inout FlatBufferBuilder,
    clientCtxOffset clientCtx: Offset = Offset()
  ) -> Offset {
    let __start = authv1_GenerateQRLoginRequest.startGenerateQRLoginRequest(&fbb)
    authv1_GenerateQRLoginRequest.add(clientCtx: clientCtx, &fbb)
    return authv1_GenerateQRLoginRequest.endGenerateQRLoginRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_GenerateQRLoginRequestT {
    return authv1_GenerateQRLoginRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_GenerateQRLoginRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_GenerateQRLoginRequestT) -> Offset {
    let __clientCtx = authv1_ClientContext.pack(&builder, obj: &obj.clientCtx)
    let __root = authv1_GenerateQRLoginRequest.startGenerateQRLoginRequest(&builder)
    authv1_GenerateQRLoginRequest.add(clientCtx: __clientCtx, &builder)
    return authv1_GenerateQRLoginRequest.endGenerateQRLoginRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.clientCtx.p, fieldName: "clientCtx", required: false, type: ForwardOffset<authv1_ClientContext>.self)
    _v.finish()
  }
}

public class authv1_GenerateQRLoginRequestT: NativeObject {

  public var clientCtx: authv1_ClientContextT?

  public init(_ _t: borrowing authv1_GenerateQRLoginRequest) {
    clientCtx = _t.clientCtx?.unpack()
  }

  public init() {
    clientCtx = authv1_ClientContextT()
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_GenerateQRLoginRequest.self) }

}
public struct authv1_GenerateQRLoginResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case token = 4
    case expiresAtMs = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var token: String? { let o = _accessor.offset(VTOFFSET.token.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var tokenSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.token.v) }
  public var expiresAtMs: Int64 { let o = _accessor.offset(VTOFFSET.expiresAtMs.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startGenerateQRLoginResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(token: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: token, at: VTOFFSET.token.p) }
  public static func add(expiresAtMs: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: expiresAtMs, def: 0, at: VTOFFSET.expiresAtMs.p) }
  public static func endGenerateQRLoginResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createGenerateQRLoginResponse(
    _ fbb: inout FlatBufferBuilder,
    tokenOffset token: Offset = Offset(),
    expiresAtMs: Int64 = 0
  ) -> Offset {
    let __start = authv1_GenerateQRLoginResponse.startGenerateQRLoginResponse(&fbb)
    authv1_GenerateQRLoginResponse.add(token: token, &fbb)
    authv1_GenerateQRLoginResponse.add(expiresAtMs: expiresAtMs, &fbb)
    return authv1_GenerateQRLoginResponse.endGenerateQRLoginResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_GenerateQRLoginResponseT {
    return authv1_GenerateQRLoginResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_GenerateQRLoginResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_GenerateQRLoginResponseT) -> Offset {
    let __token: Offset
    if let s = obj.token {
      __token = builder.create(string: s)
    } else {
      __token = Offset()
    }

    let __root = authv1_GenerateQRLoginResponse.startGenerateQRLoginResponse(&builder)
    authv1_GenerateQRLoginResponse.add(token: __token, &builder)
    authv1_GenerateQRLoginResponse.add(expiresAtMs: obj.expiresAtMs, &builder)
    return authv1_GenerateQRLoginResponse.endGenerateQRLoginResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.token.p, fieldName: "token", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.expiresAtMs.p, fieldName: "expiresAtMs", required: false, type: Int64.self)
    _v.finish()
  }
}

public class authv1_GenerateQRLoginResponseT: NativeObject {

  public var token: String?
  public var expiresAtMs: Int64

  public init(_ _t: borrowing authv1_GenerateQRLoginResponse) {
    token = _t.token
    expiresAtMs = _t.expiresAtMs
  }

  public init() {
    expiresAtMs = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_GenerateQRLoginResponse.self) }

}
public struct authv1_ScanQRLoginRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case token = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var token: String? { let o = _accessor.offset(VTOFFSET.token.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var tokenSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.token.v) }
  public static func startScanQRLoginRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(token: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: token, at: VTOFFSET.token.p) }
  public static func endScanQRLoginRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createScanQRLoginRequest(
    _ fbb: inout FlatBufferBuilder,
    tokenOffset token: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ScanQRLoginRequest.startScanQRLoginRequest(&fbb)
    authv1_ScanQRLoginRequest.add(token: token, &fbb)
    return authv1_ScanQRLoginRequest.endScanQRLoginRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_ScanQRLoginRequestT {
    return authv1_ScanQRLoginRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ScanQRLoginRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ScanQRLoginRequestT) -> Offset {
    let __token: Offset
    if let s = obj.token {
      __token = builder.create(string: s)
    } else {
      __token = Offset()
    }

    let __root = authv1_ScanQRLoginRequest.startScanQRLoginRequest(&builder)
    authv1_ScanQRLoginRequest.add(token: __token, &builder)
    return authv1_ScanQRLoginRequest.endScanQRLoginRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.token.p, fieldName: "token", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_ScanQRLoginRequestT: NativeObject {

  public var token: String?

  public init(_ _t: borrowing authv1_ScanQRLoginRequest) {
    token = _t.token
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ScanQRLoginRequest.self) }

}
public struct authv1_ScanQRLoginResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ok = 4
    case failReason = 6
    case waiterDeviceName = 8
    case waiterPlatform = 10
    case waiterOs = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ok: Bool { let o = _accessor.offset(VTOFFSET.ok.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var failReason: authv1_QRLoginFailReason { let o = _accessor.offset(VTOFFSET.failReason.v); return o == 0 ? .unknown : authv1_QRLoginFailReason(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var waiterDeviceName: String? { let o = _accessor.offset(VTOFFSET.waiterDeviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var waiterDeviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.waiterDeviceName.v) }
  public var waiterPlatform: authv1_Platform { let o = _accessor.offset(VTOFFSET.waiterPlatform.v); return o == 0 ? .unknown : authv1_Platform(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var waiterOs: String? { let o = _accessor.offset(VTOFFSET.waiterOs.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var waiterOsSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.waiterOs.v) }
  public static func startScanQRLoginResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(ok: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: ok, def: false,
   at: VTOFFSET.ok.p) }
  public static func add(failReason: authv1_QRLoginFailReason, _ fbb: inout FlatBufferBuilder) { fbb.add(element: failReason.rawValue, def: 0, at: VTOFFSET.failReason.p) }
  public static func add(waiterDeviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: waiterDeviceName, at: VTOFFSET.waiterDeviceName.p) }
  public static func add(waiterPlatform: authv1_Platform, _ fbb: inout FlatBufferBuilder) { fbb.add(element: waiterPlatform.rawValue, def: 0, at: VTOFFSET.waiterPlatform.p) }
  public static func add(waiterOs: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: waiterOs, at: VTOFFSET.waiterOs.p) }
  public static func endScanQRLoginResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createScanQRLoginResponse(
    _ fbb: inout FlatBufferBuilder,
    ok: Bool = false,
    failReason: authv1_QRLoginFailReason = .unknown,
    waiterDeviceNameOffset waiterDeviceName: Offset = Offset(),
    waiterPlatform: authv1_Platform = .unknown,
    waiterOsOffset waiterOs: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ScanQRLoginResponse.startScanQRLoginResponse(&fbb)
    authv1_ScanQRLoginResponse.add(ok: ok, &fbb)
    authv1_ScanQRLoginResponse.add(failReason: failReason, &fbb)
    authv1_ScanQRLoginResponse.add(waiterDeviceName: waiterDeviceName, &fbb)
    authv1_ScanQRLoginResponse.add(waiterPlatform: waiterPlatform, &fbb)
    authv1_ScanQRLoginResponse.add(waiterOs: waiterOs, &fbb)
    return authv1_ScanQRLoginResponse.endScanQRLoginResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_ScanQRLoginResponseT {
    return authv1_ScanQRLoginResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ScanQRLoginResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ScanQRLoginResponseT) -> Offset {
    let __waiterDeviceName: Offset
    if let s = obj.waiterDeviceName {
      __waiterDeviceName = builder.create(string: s)
    } else {
      __waiterDeviceName = Offset()
    }

    let __waiterOs: Offset
    if let s = obj.waiterOs {
      __waiterOs = builder.create(string: s)
    } else {
      __waiterOs = Offset()
    }

    let __root = authv1_ScanQRLoginResponse.startScanQRLoginResponse(&builder)
    authv1_ScanQRLoginResponse.add(ok: obj.ok, &builder)
    authv1_ScanQRLoginResponse.add(failReason: obj.failReason, &builder)
    authv1_ScanQRLoginResponse.add(waiterDeviceName: __waiterDeviceName, &builder)
    authv1_ScanQRLoginResponse.add(waiterPlatform: obj.waiterPlatform, &builder)
    authv1_ScanQRLoginResponse.add(waiterOs: __waiterOs, &builder)
    return authv1_ScanQRLoginResponse.endScanQRLoginResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ok.p, fieldName: "ok", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.failReason.p, fieldName: "failReason", required: false, type: authv1_QRLoginFailReason.self)
    try _v.visit(field: VTOFFSET.waiterDeviceName.p, fieldName: "waiterDeviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.waiterPlatform.p, fieldName: "waiterPlatform", required: false, type: authv1_Platform.self)
    try _v.visit(field: VTOFFSET.waiterOs.p, fieldName: "waiterOs", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_ScanQRLoginResponseT: NativeObject {

  public var ok: Bool
  public var failReason: authv1_QRLoginFailReason
  public var waiterDeviceName: String?
  public var waiterPlatform: authv1_Platform
  public var waiterOs: String?

  public init(_ _t: borrowing authv1_ScanQRLoginResponse) {
    ok = _t.ok
    failReason = _t.failReason
    waiterDeviceName = _t.waiterDeviceName
    waiterPlatform = _t.waiterPlatform
    waiterOs = _t.waiterOs
  }

  public init() {
    ok = false
    failReason = .unknown
    waiterPlatform = .unknown
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ScanQRLoginResponse.self) }

}
public struct authv1_ConfirmQRLoginRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case token = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var token: String? { let o = _accessor.offset(VTOFFSET.token.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var tokenSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.token.v) }
  public static func startConfirmQRLoginRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(token: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: token, at: VTOFFSET.token.p) }
  public static func endConfirmQRLoginRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createConfirmQRLoginRequest(
    _ fbb: inout FlatBufferBuilder,
    tokenOffset token: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ConfirmQRLoginRequest.startConfirmQRLoginRequest(&fbb)
    authv1_ConfirmQRLoginRequest.add(token: token, &fbb)
    return authv1_ConfirmQRLoginRequest.endConfirmQRLoginRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_ConfirmQRLoginRequestT {
    return authv1_ConfirmQRLoginRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ConfirmQRLoginRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ConfirmQRLoginRequestT) -> Offset {
    let __token: Offset
    if let s = obj.token {
      __token = builder.create(string: s)
    } else {
      __token = Offset()
    }

    let __root = authv1_ConfirmQRLoginRequest.startConfirmQRLoginRequest(&builder)
    authv1_ConfirmQRLoginRequest.add(token: __token, &builder)
    return authv1_ConfirmQRLoginRequest.endConfirmQRLoginRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.token.p, fieldName: "token", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_ConfirmQRLoginRequestT: NativeObject {

  public var token: String?

  public init(_ _t: borrowing authv1_ConfirmQRLoginRequest) {
    token = _t.token
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ConfirmQRLoginRequest.self) }

}
public struct authv1_ConfirmQRLoginResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ok = 4
    case failReason = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ok: Bool { let o = _accessor.offset(VTOFFSET.ok.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var failReason: authv1_QRLoginFailReason { let o = _accessor.offset(VTOFFSET.failReason.v); return o == 0 ? .unknown : authv1_QRLoginFailReason(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public static func startConfirmQRLoginResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(ok: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: ok, def: false,
   at: VTOFFSET.ok.p) }
  public static func add(failReason: authv1_QRLoginFailReason, _ fbb: inout FlatBufferBuilder) { fbb.add(element: failReason.rawValue, def: 0, at: VTOFFSET.failReason.p) }
  public static func endConfirmQRLoginResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createConfirmQRLoginResponse(
    _ fbb: inout FlatBufferBuilder,
    ok: Bool = false,
    failReason: authv1_QRLoginFailReason = .unknown
  ) -> Offset {
    let __start = authv1_ConfirmQRLoginResponse.startConfirmQRLoginResponse(&fbb)
    authv1_ConfirmQRLoginResponse.add(ok: ok, &fbb)
    authv1_ConfirmQRLoginResponse.add(failReason: failReason, &fbb)
    return authv1_ConfirmQRLoginResponse.endConfirmQRLoginResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_ConfirmQRLoginResponseT {
    return authv1_ConfirmQRLoginResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ConfirmQRLoginResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ConfirmQRLoginResponseT) -> Offset {
    let __root = authv1_ConfirmQRLoginResponse.startConfirmQRLoginResponse(&builder)
    authv1_ConfirmQRLoginResponse.add(ok: obj.ok, &builder)
    authv1_ConfirmQRLoginResponse.add(failReason: obj.failReason, &builder)
    return authv1_ConfirmQRLoginResponse.endConfirmQRLoginResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ok.p, fieldName: "ok", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.failReason.p, fieldName: "failReason", required: false, type: authv1_QRLoginFailReason.self)
    _v.finish()
  }
}

public class authv1_ConfirmQRLoginResponseT: NativeObject {

  public var ok: Bool
  public var failReason: authv1_QRLoginFailReason

  public init(_ _t: borrowing authv1_ConfirmQRLoginResponse) {
    ok = _t.ok
    failReason = _t.failReason
  }

  public init() {
    ok = false
    failReason = .unknown
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ConfirmQRLoginResponse.self) }

}
public struct authv1_RejectQRLoginRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case token = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var token: String? { let o = _accessor.offset(VTOFFSET.token.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var tokenSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.token.v) }
  public static func startRejectQRLoginRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(token: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: token, at: VTOFFSET.token.p) }
  public static func endRejectQRLoginRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createRejectQRLoginRequest(
    _ fbb: inout FlatBufferBuilder,
    tokenOffset token: Offset = Offset()
  ) -> Offset {
    let __start = authv1_RejectQRLoginRequest.startRejectQRLoginRequest(&fbb)
    authv1_RejectQRLoginRequest.add(token: token, &fbb)
    return authv1_RejectQRLoginRequest.endRejectQRLoginRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_RejectQRLoginRequestT {
    return authv1_RejectQRLoginRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_RejectQRLoginRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_RejectQRLoginRequestT) -> Offset {
    let __token: Offset
    if let s = obj.token {
      __token = builder.create(string: s)
    } else {
      __token = Offset()
    }

    let __root = authv1_RejectQRLoginRequest.startRejectQRLoginRequest(&builder)
    authv1_RejectQRLoginRequest.add(token: __token, &builder)
    return authv1_RejectQRLoginRequest.endRejectQRLoginRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.token.p, fieldName: "token", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_RejectQRLoginRequestT: NativeObject {

  public var token: String?

  public init(_ _t: borrowing authv1_RejectQRLoginRequest) {
    token = _t.token
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_RejectQRLoginRequest.self) }

}
public struct authv1_RejectQRLoginResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ok = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ok: Bool { let o = _accessor.offset(VTOFFSET.ok.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startRejectQRLoginResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ok: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: ok, def: false,
   at: VTOFFSET.ok.p) }
  public static func endRejectQRLoginResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createRejectQRLoginResponse(
    _ fbb: inout FlatBufferBuilder,
    ok: Bool = false
  ) -> Offset {
    let __start = authv1_RejectQRLoginResponse.startRejectQRLoginResponse(&fbb)
    authv1_RejectQRLoginResponse.add(ok: ok, &fbb)
    return authv1_RejectQRLoginResponse.endRejectQRLoginResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_RejectQRLoginResponseT {
    return authv1_RejectQRLoginResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_RejectQRLoginResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_RejectQRLoginResponseT) -> Offset {
    let __root = authv1_RejectQRLoginResponse.startRejectQRLoginResponse(&builder)
    authv1_RejectQRLoginResponse.add(ok: obj.ok, &builder)
    return authv1_RejectQRLoginResponse.endRejectQRLoginResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ok.p, fieldName: "ok", required: false, type: Bool.self)
    _v.finish()
  }
}

public class authv1_RejectQRLoginResponseT: NativeObject {

  public var ok: Bool

  public init(_ _t: borrowing authv1_RejectQRLoginResponse) {
    ok = _t.ok
  }

  public init() {
    ok = false
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_RejectQRLoginResponse.self) }

}
public struct authv1_QRLoginConfirmed: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    case resumeSecret = 6
    case userId = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var resumeSecret: String? { let o = _accessor.offset(VTOFFSET.resumeSecret.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var resumeSecretSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.resumeSecret.v) }
  public var userId: Int32 { let o = _accessor.offset(VTOFFSET.userId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startQRLoginConfirmed(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func add(resumeSecret: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resumeSecret, at: VTOFFSET.resumeSecret.p) }
  public static func add(userId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: userId, def: 0, at: VTOFFSET.userId.p) }
  public static func endQRLoginConfirmed(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createQRLoginConfirmed(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0,
    resumeSecretOffset resumeSecret: Offset = Offset(),
    userId: Int32 = 0
  ) -> Offset {
    let __start = authv1_QRLoginConfirmed.startQRLoginConfirmed(&fbb)
    authv1_QRLoginConfirmed.add(authKeyId: authKeyId, &fbb)
    authv1_QRLoginConfirmed.add(resumeSecret: resumeSecret, &fbb)
    authv1_QRLoginConfirmed.add(userId: userId, &fbb)
    return authv1_QRLoginConfirmed.endQRLoginConfirmed(&fbb, start: __start)
  }

  public func unpack() -> authv1_QRLoginConfirmedT {
    return authv1_QRLoginConfirmedT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginConfirmedT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginConfirmedT) -> Offset {
    let __resumeSecret: Offset
    if let s = obj.resumeSecret {
      __resumeSecret = builder.create(string: s)
    } else {
      __resumeSecret = Offset()
    }

    let __root = authv1_QRLoginConfirmed.startQRLoginConfirmed(&builder)
    authv1_QRLoginConfirmed.add(authKeyId: obj.authKeyId, &builder)
    authv1_QRLoginConfirmed.add(resumeSecret: __resumeSecret, &builder)
    authv1_QRLoginConfirmed.add(userId: obj.userId, &builder)
    return authv1_QRLoginConfirmed.endQRLoginConfirmed(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.resumeSecret.p, fieldName: "resumeSecret", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.userId.p, fieldName: "userId", required: false, type: Int32.self)
    _v.finish()
  }
}

public class authv1_QRLoginConfirmedT: NativeObject {

  public var authKeyId: UInt64
  public var resumeSecret: String?
  public var userId: Int32

  public init(_ _t: borrowing authv1_QRLoginConfirmed) {
    authKeyId = _t.authKeyId
    resumeSecret = _t.resumeSecret
    userId = _t.userId
  }

  public init() {
    authKeyId = 0
    userId = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_QRLoginConfirmed.self) }

}
public struct authv1_QRLoginExpiredOrRejected: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case reason = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var reason: authv1_QRLoginFailReason { let o = _accessor.offset(VTOFFSET.reason.v); return o == 0 ? .unknown : authv1_QRLoginFailReason(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public static func startQRLoginExpiredOrRejected(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(reason: authv1_QRLoginFailReason, _ fbb: inout FlatBufferBuilder) { fbb.add(element: reason.rawValue, def: 0, at: VTOFFSET.reason.p) }
  public static func endQRLoginExpiredOrRejected(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createQRLoginExpiredOrRejected(
    _ fbb: inout FlatBufferBuilder,
    reason: authv1_QRLoginFailReason = .unknown
  ) -> Offset {
    let __start = authv1_QRLoginExpiredOrRejected.startQRLoginExpiredOrRejected(&fbb)
    authv1_QRLoginExpiredOrRejected.add(reason: reason, &fbb)
    return authv1_QRLoginExpiredOrRejected.endQRLoginExpiredOrRejected(&fbb, start: __start)
  }

  public func unpack() -> authv1_QRLoginExpiredOrRejectedT {
    return authv1_QRLoginExpiredOrRejectedT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginExpiredOrRejectedT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginExpiredOrRejectedT) -> Offset {
    let __root = authv1_QRLoginExpiredOrRejected.startQRLoginExpiredOrRejected(&builder)
    authv1_QRLoginExpiredOrRejected.add(reason: obj.reason, &builder)
    return authv1_QRLoginExpiredOrRejected.endQRLoginExpiredOrRejected(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.reason.p, fieldName: "reason", required: false, type: authv1_QRLoginFailReason.self)
    _v.finish()
  }
}

public class authv1_QRLoginExpiredOrRejectedT: NativeObject {

  public var reason: authv1_QRLoginFailReason

  public init(_ _t: borrowing authv1_QRLoginExpiredOrRejected) {
    reason = _t.reason
  }

  public init() {
    reason = .unknown
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_QRLoginExpiredOrRejected.self) }

}
public struct authv1_WaitQRLoginResultRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case token = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var token: String? { let o = _accessor.offset(VTOFFSET.token.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var tokenSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.token.v) }
  public static func startWaitQRLoginResultRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(token: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: token, at: VTOFFSET.token.p) }
  public static func endWaitQRLoginResultRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createWaitQRLoginResultRequest(
    _ fbb: inout FlatBufferBuilder,
    tokenOffset token: Offset = Offset()
  ) -> Offset {
    let __start = authv1_WaitQRLoginResultRequest.startWaitQRLoginResultRequest(&fbb)
    authv1_WaitQRLoginResultRequest.add(token: token, &fbb)
    return authv1_WaitQRLoginResultRequest.endWaitQRLoginResultRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_WaitQRLoginResultRequestT {
    return authv1_WaitQRLoginResultRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_WaitQRLoginResultRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_WaitQRLoginResultRequestT) -> Offset {
    let __token: Offset
    if let s = obj.token {
      __token = builder.create(string: s)
    } else {
      __token = Offset()
    }

    let __root = authv1_WaitQRLoginResultRequest.startWaitQRLoginResultRequest(&builder)
    authv1_WaitQRLoginResultRequest.add(token: __token, &builder)
    return authv1_WaitQRLoginResultRequest.endWaitQRLoginResultRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.token.p, fieldName: "token", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_WaitQRLoginResultRequestT: NativeObject {

  public var token: String?

  public init(_ _t: borrowing authv1_WaitQRLoginResultRequest) {
    token = _t.token
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_WaitQRLoginResultRequest.self) }

}
public struct authv1_QRLoginEvent: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case payloadType = 4
    case payload = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var payloadType: authv1_QRLoginEventPayload { let o = _accessor.offset(VTOFFSET.payloadType.v); return o == 0 ? .none_ : authv1_QRLoginEventPayload(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func payload<T: FlatbuffersInitializable>(type: T.Type) -> T? { let o = _accessor.offset(VTOFFSET.payload.v); return o == 0 ? nil : _accessor.union(o) }
  public static func startQRLoginEvent(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(payloadType: authv1_QRLoginEventPayload, _ fbb: inout FlatBufferBuilder) { fbb.add(element: payloadType.rawValue, def: 0, at: VTOFFSET.payloadType.p) }
  public static func add(payload: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: payload, at: VTOFFSET.payload.p) }
  public static func endQRLoginEvent(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createQRLoginEvent(
    _ fbb: inout FlatBufferBuilder,
    payloadType: authv1_QRLoginEventPayload = .none_,
    payloadOffset payload: Offset = Offset()
  ) -> Offset {
    let __start = authv1_QRLoginEvent.startQRLoginEvent(&fbb)
    authv1_QRLoginEvent.add(payloadType: payloadType, &fbb)
    authv1_QRLoginEvent.add(payload: payload, &fbb)
    return authv1_QRLoginEvent.endQRLoginEvent(&fbb, start: __start)
  }

  public func unpack() -> authv1_QRLoginEventT {
    return authv1_QRLoginEventT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginEventT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_QRLoginEventT) -> Offset {
    let __payload = obj.payload?.pack(builder: &builder) ?? Offset()
    let __root = authv1_QRLoginEvent.startQRLoginEvent(&builder)
    if let o = obj.payload?.type {
      authv1_QRLoginEvent.add(payloadType: o, &builder)
      authv1_QRLoginEvent.add(payload: __payload, &builder)
    }

    return authv1_QRLoginEvent.endQRLoginEvent(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.payloadType.p, unionField: VTOFFSET.payload.p, unionKeyName: "payloadType", fieldName: "payload", required: false, completion: { (verifier, key: authv1_QRLoginEventPayload, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .qrloginconfirmed:
        try ForwardOffset<authv1_QRLoginConfirmed>.verify(&verifier, at: pos, of: authv1_QRLoginConfirmed.self)
      case .qrloginexpiredorrejected:
        try ForwardOffset<authv1_QRLoginExpiredOrRejected>.verify(&verifier, at: pos, of: authv1_QRLoginExpiredOrRejected.self)
      }
    })
    _v.finish()
  }
}

public class authv1_QRLoginEventT: NativeObject {

  public var payload: authv1_QRLoginEventPayloadUnion?

  public init(_ _t: borrowing authv1_QRLoginEvent) {
    switch _t.payloadType {
    case .qrloginconfirmed:
      let _v = _t.payload(type: authv1_QRLoginConfirmed.self)
      payload = authv1_QRLoginEventPayloadUnion(_v?.unpack(), type: .qrloginconfirmed)
    case .qrloginexpiredorrejected:
      let _v = _t.payload(type: authv1_QRLoginExpiredOrRejected.self)
      payload = authv1_QRLoginEventPayloadUnion(_v?.unpack(), type: .qrloginexpiredorrejected)
    default: break
    }
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_QRLoginEvent.self) }

}
