// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public struct authv1_ResumeSessionRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    case resumeSecret = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var resumeSecret: String? { let o = _accessor.offset(VTOFFSET.resumeSecret.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var resumeSecretSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.resumeSecret.v) }
  public static func startResumeSessionRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func add(resumeSecret: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resumeSecret, at: VTOFFSET.resumeSecret.p) }
  public static func endResumeSessionRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createResumeSessionRequest(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0,
    resumeSecretOffset resumeSecret: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ResumeSessionRequest.startResumeSessionRequest(&fbb)
    authv1_ResumeSessionRequest.add(authKeyId: authKeyId, &fbb)
    authv1_ResumeSessionRequest.add(resumeSecret: resumeSecret, &fbb)
    return authv1_ResumeSessionRequest.endResumeSessionRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_ResumeSessionRequestT {
    return authv1_ResumeSessionRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ResumeSessionRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ResumeSessionRequestT) -> Offset {
    let __resumeSecret: Offset
    if let s = obj.resumeSecret {
      __resumeSecret = builder.create(string: s)
    } else {
      __resumeSecret = Offset()
    }

    let __root = authv1_ResumeSessionRequest.startResumeSessionRequest(&builder)
    authv1_ResumeSessionRequest.add(authKeyId: obj.authKeyId, &builder)
    authv1_ResumeSessionRequest.add(resumeSecret: __resumeSecret, &builder)
    return authv1_ResumeSessionRequest.endResumeSessionRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.resumeSecret.p, fieldName: "resumeSecret", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_ResumeSessionRequestT: NativeObject {

  public var authKeyId: UInt64
  public var resumeSecret: String?

  public init(_ _t: borrowing authv1_ResumeSessionRequest) {
    authKeyId = _t.authKeyId
    resumeSecret = _t.resumeSecret
  }

  public init() {
    authKeyId = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ResumeSessionRequest.self) }

}
public struct authv1_ResumeSessionResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    case userId = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var userId: Int32 { let o = _accessor.offset(VTOFFSET.userId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startResumeSessionResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func add(userId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: userId, def: 0, at: VTOFFSET.userId.p) }
  public static func endResumeSessionResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createResumeSessionResponse(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0,
    userId: Int32 = 0
  ) -> Offset {
    let __start = authv1_ResumeSessionResponse.startResumeSessionResponse(&fbb)
    authv1_ResumeSessionResponse.add(authKeyId: authKeyId, &fbb)
    authv1_ResumeSessionResponse.add(userId: userId, &fbb)
    return authv1_ResumeSessionResponse.endResumeSessionResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_ResumeSessionResponseT {
    return authv1_ResumeSessionResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ResumeSessionResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ResumeSessionResponseT) -> Offset {
    let __root = authv1_ResumeSessionResponse.startResumeSessionResponse(&builder)
    authv1_ResumeSessionResponse.add(authKeyId: obj.authKeyId, &builder)
    authv1_ResumeSessionResponse.add(userId: obj.userId, &builder)
    return authv1_ResumeSessionResponse.endResumeSessionResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.userId.p, fieldName: "userId", required: false, type: Int32.self)
    _v.finish()
  }
}

public class authv1_ResumeSessionResponseT: NativeObject {

  public var authKeyId: UInt64
  public var userId: Int32

  public init(_ _t: borrowing authv1_ResumeSessionResponse) {
    authKeyId = _t.authKeyId
    userId = _t.userId
  }

  public init() {
    authKeyId = 0
    userId = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ResumeSessionResponse.self) }

}
public struct authv1_TerminateSessionRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case reason = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var reason: String? { let o = _accessor.offset(VTOFFSET.reason.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var reasonSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.reason.v) }
  public static func startTerminateSessionRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(reason: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: reason, at: VTOFFSET.reason.p) }
  public static func endTerminateSessionRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTerminateSessionRequest(
    _ fbb: inout FlatBufferBuilder,
    reasonOffset reason: Offset = Offset()
  ) -> Offset {
    let __start = authv1_TerminateSessionRequest.startTerminateSessionRequest(&fbb)
    authv1_TerminateSessionRequest.add(reason: reason, &fbb)
    return authv1_TerminateSessionRequest.endTerminateSessionRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_TerminateSessionRequestT {
    return authv1_TerminateSessionRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_TerminateSessionRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_TerminateSessionRequestT) -> Offset {
    let __reason: Offset
    if let s = obj.reason {
      __reason = builder.create(string: s)
    } else {
      __reason = Offset()
    }

    let __root = authv1_TerminateSessionRequest.startTerminateSessionRequest(&builder)
    authv1_TerminateSessionRequest.add(reason: __reason, &builder)
    return authv1_TerminateSessionRequest.endTerminateSessionRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.reason.p, fieldName: "reason", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public class authv1_TerminateSessionRequestT: NativeObject {

  public var reason: String?

  public init(_ _t: borrowing authv1_TerminateSessionRequest) {
    reason = _t.reason
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_TerminateSessionRequest.self) }

}
public struct authv1_TerminateSessionResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ok = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ok: Bool { let o = _accessor.offset(VTOFFSET.ok.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startTerminateSessionResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ok: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: ok, def: false,
   at: VTOFFSET.ok.p) }
  public static func endTerminateSessionResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTerminateSessionResponse(
    _ fbb: inout FlatBufferBuilder,
    ok: Bool = false
  ) -> Offset {
    let __start = authv1_TerminateSessionResponse.startTerminateSessionResponse(&fbb)
    authv1_TerminateSessionResponse.add(ok: ok, &fbb)
    return authv1_TerminateSessionResponse.endTerminateSessionResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_TerminateSessionResponseT {
    return authv1_TerminateSessionResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_TerminateSessionResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_TerminateSessionResponseT) -> Offset {
    let __root = authv1_TerminateSessionResponse.startTerminateSessionResponse(&builder)
    authv1_TerminateSessionResponse.add(ok: obj.ok, &builder)
    return authv1_TerminateSessionResponse.endTerminateSessionResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ok.p, fieldName: "ok", required: false, type: Bool.self)
    _v.finish()
  }
}

public class authv1_TerminateSessionResponseT: NativeObject {

  public var ok: Bool

  public init(_ _t: borrowing authv1_TerminateSessionResponse) {
    ok = _t.ok
  }

  public init() {
    ok = false
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_TerminateSessionResponse.self) }

}
public struct authv1_ListSessionsRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startListSessionsRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endListSessionsRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public func unpack() -> authv1_ListSessionsRequestT {
    return authv1_ListSessionsRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ListSessionsRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ListSessionsRequestT) -> Offset {
    let __root = authv1_ListSessionsRequest.startListSessionsRequest(&builder)
    return authv1_ListSessionsRequest.endListSessionsRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public class authv1_ListSessionsRequestT: NativeObject {


  public init(_ _t: borrowing authv1_ListSessionsRequest) {
  }

  public init() {
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ListSessionsRequest.self) }

}
public struct authv1_SessionInfo: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    case isCurrent = 6
    case platform = 8
    case os = 10
    case deviceName = 12
    case ipAddress = 14
    case createdAtMs = 16
    case lastActiveAtMs = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var isCurrent: Bool { let o = _accessor.offset(VTOFFSET.isCurrent.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var platform: authv1_Platform { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? .unknown : authv1_Platform(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var os: String? { let o = _accessor.offset(VTOFFSET.os.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var osSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.os.v) }
  public var deviceName: String? { let o = _accessor.offset(VTOFFSET.deviceName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var deviceNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.deviceName.v) }
  public var ipAddress: String? { let o = _accessor.offset(VTOFFSET.ipAddress.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var ipAddressSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.ipAddress.v) }
  public var createdAtMs: Int64 { let o = _accessor.offset(VTOFFSET.createdAtMs.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var lastActiveAtMs: Int64 { let o = _accessor.offset(VTOFFSET.lastActiveAtMs.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startSessionInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func add(isCurrent: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isCurrent, def: false,
   at: VTOFFSET.isCurrent.p) }
  public static func add(platform: authv1_Platform, _ fbb: inout FlatBufferBuilder) { fbb.add(element: platform.rawValue, def: 0, at: VTOFFSET.platform.p) }
  public static func add(os: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: os, at: VTOFFSET.os.p) }
  public static func add(deviceName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: deviceName, at: VTOFFSET.deviceName.p) }
  public static func add(ipAddress: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: ipAddress, at: VTOFFSET.ipAddress.p) }
  public static func add(createdAtMs: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: createdAtMs, def: 0, at: VTOFFSET.createdAtMs.p) }
  public static func add(lastActiveAtMs: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lastActiveAtMs, def: 0, at: VTOFFSET.lastActiveAtMs.p) }
  public static func endSessionInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createSessionInfo(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0,
    isCurrent: Bool = false,
    platform: authv1_Platform = .unknown,
    osOffset os: Offset = Offset(),
    deviceNameOffset deviceName: Offset = Offset(),
    ipAddressOffset ipAddress: Offset = Offset(),
    createdAtMs: Int64 = 0,
    lastActiveAtMs: Int64 = 0
  ) -> Offset {
    let __start = authv1_SessionInfo.startSessionInfo(&fbb)
    authv1_SessionInfo.add(authKeyId: authKeyId, &fbb)
    authv1_SessionInfo.add(isCurrent: isCurrent, &fbb)
    authv1_SessionInfo.add(platform: platform, &fbb)
    authv1_SessionInfo.add(os: os, &fbb)
    authv1_SessionInfo.add(deviceName: deviceName, &fbb)
    authv1_SessionInfo.add(ipAddress: ipAddress, &fbb)
    authv1_SessionInfo.add(createdAtMs: createdAtMs, &fbb)
    authv1_SessionInfo.add(lastActiveAtMs: lastActiveAtMs, &fbb)
    return authv1_SessionInfo.endSessionInfo(&fbb, start: __start)
  }

  public func unpack() -> authv1_SessionInfoT {
    return authv1_SessionInfoT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_SessionInfoT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_SessionInfoT) -> Offset {
    let __os: Offset
    if let s = obj.os {
      __os = builder.create(string: s)
    } else {
      __os = Offset()
    }

    let __deviceName: Offset
    if let s = obj.deviceName {
      __deviceName = builder.create(string: s)
    } else {
      __deviceName = Offset()
    }

    let __ipAddress: Offset
    if let s = obj.ipAddress {
      __ipAddress = builder.create(string: s)
    } else {
      __ipAddress = Offset()
    }

    let __root = authv1_SessionInfo.startSessionInfo(&builder)
    authv1_SessionInfo.add(authKeyId: obj.authKeyId, &builder)
    authv1_SessionInfo.add(isCurrent: obj.isCurrent, &builder)
    authv1_SessionInfo.add(platform: obj.platform, &builder)
    authv1_SessionInfo.add(os: __os, &builder)
    authv1_SessionInfo.add(deviceName: __deviceName, &builder)
    authv1_SessionInfo.add(ipAddress: __ipAddress, &builder)
    authv1_SessionInfo.add(createdAtMs: obj.createdAtMs, &builder)
    authv1_SessionInfo.add(lastActiveAtMs: obj.lastActiveAtMs, &builder)
    return authv1_SessionInfo.endSessionInfo(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.isCurrent.p, fieldName: "isCurrent", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: authv1_Platform.self)
    try _v.visit(field: VTOFFSET.os.p, fieldName: "os", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.deviceName.p, fieldName: "deviceName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.ipAddress.p, fieldName: "ipAddress", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.createdAtMs.p, fieldName: "createdAtMs", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.lastActiveAtMs.p, fieldName: "lastActiveAtMs", required: false, type: Int64.self)
    _v.finish()
  }
}

public class authv1_SessionInfoT: NativeObject {

  public var authKeyId: UInt64
  public var isCurrent: Bool
  public var platform: authv1_Platform
  public var os: String?
  public var deviceName: String?
  public var ipAddress: String?
  public var createdAtMs: Int64
  public var lastActiveAtMs: Int64

  public init(_ _t: borrowing authv1_SessionInfo) {
    authKeyId = _t.authKeyId
    isCurrent = _t.isCurrent
    platform = _t.platform
    os = _t.os
    deviceName = _t.deviceName
    ipAddress = _t.ipAddress
    createdAtMs = _t.createdAtMs
    lastActiveAtMs = _t.lastActiveAtMs
  }

  public init() {
    authKeyId = 0
    isCurrent = false
    platform = .unknown
    createdAtMs = 0
    lastActiveAtMs = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_SessionInfo.self) }

}
public struct authv1_ListSessionsResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sessions = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sessions: FlatbufferVector<authv1_SessionInfo> { return _accessor.vector(at: VTOFFSET.sessions.v, byteSize: 4) }
  public static func startListSessionsResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func addVectorOf(sessions: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sessions, at: VTOFFSET.sessions.p) }
  public static func endListSessionsResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createListSessionsResponse(
    _ fbb: inout FlatBufferBuilder,
    sessionsVectorOffset sessions: Offset = Offset()
  ) -> Offset {
    let __start = authv1_ListSessionsResponse.startListSessionsResponse(&fbb)
    authv1_ListSessionsResponse.addVectorOf(sessions: sessions, &fbb)
    return authv1_ListSessionsResponse.endListSessionsResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_ListSessionsResponseT {
    return authv1_ListSessionsResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ListSessionsResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_ListSessionsResponseT) -> Offset {
    var __sessions__: [Offset] = []
    for var i in obj.sessions {
      __sessions__.append(authv1_SessionInfo.pack(&builder, obj: &i))
    }
    let __sessions = builder.createVector(ofOffsets: __sessions__)
    let __root = authv1_ListSessionsResponse.startListSessionsResponse(&builder)
    authv1_ListSessionsResponse.addVectorOf(sessions: __sessions, &builder)
    return authv1_ListSessionsResponse.endListSessionsResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sessions.p, fieldName: "sessions", required: false, type: ForwardOffset<Vector<ForwardOffset<authv1_SessionInfo>, authv1_SessionInfo>>.self)
    _v.finish()
  }
}

public class authv1_ListSessionsResponseT: NativeObject {

  public var sessions: [authv1_SessionInfoT?]

  public init(_ _t: borrowing authv1_ListSessionsResponse) {
    sessions = []
    for val in _t.sessions{
        sessions.append(val.unpack())
    }
  }

  public init() {
    sessions = []
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_ListSessionsResponse.self) }

}
public struct authv1_KillSessionRequest: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case authKeyId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var authKeyId: UInt64 { let o = _accessor.offset(VTOFFSET.authKeyId.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startKillSessionRequest(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(authKeyId: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: authKeyId, def: 0, at: VTOFFSET.authKeyId.p) }
  public static func endKillSessionRequest(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createKillSessionRequest(
    _ fbb: inout FlatBufferBuilder,
    authKeyId: UInt64 = 0
  ) -> Offset {
    let __start = authv1_KillSessionRequest.startKillSessionRequest(&fbb)
    authv1_KillSessionRequest.add(authKeyId: authKeyId, &fbb)
    return authv1_KillSessionRequest.endKillSessionRequest(&fbb, start: __start)
  }

  public func unpack() -> authv1_KillSessionRequestT {
    return authv1_KillSessionRequestT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_KillSessionRequestT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_KillSessionRequestT) -> Offset {
    let __root = authv1_KillSessionRequest.startKillSessionRequest(&builder)
    authv1_KillSessionRequest.add(authKeyId: obj.authKeyId, &builder)
    return authv1_KillSessionRequest.endKillSessionRequest(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.authKeyId.p, fieldName: "authKeyId", required: false, type: UInt64.self)
    _v.finish()
  }
}

public class authv1_KillSessionRequestT: NativeObject {

  public var authKeyId: UInt64

  public init(_ _t: borrowing authv1_KillSessionRequest) {
    authKeyId = _t.authKeyId
  }

  public init() {
    authKeyId = 0
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_KillSessionRequest.self) }

}
public struct authv1_KillSessionResponse: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable, ObjectAPIPacker {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case ok = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var ok: Bool { let o = _accessor.offset(VTOFFSET.ok.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startKillSessionResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(ok: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: ok, def: false,
   at: VTOFFSET.ok.p) }
  public static func endKillSessionResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createKillSessionResponse(
    _ fbb: inout FlatBufferBuilder,
    ok: Bool = false
  ) -> Offset {
    let __start = authv1_KillSessionResponse.startKillSessionResponse(&fbb)
    authv1_KillSessionResponse.add(ok: ok, &fbb)
    return authv1_KillSessionResponse.endKillSessionResponse(&fbb, start: __start)
  }

  public func unpack() -> authv1_KillSessionResponseT {
    return authv1_KillSessionResponseT(self)
  }
  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_KillSessionResponseT?) -> Offset {
    guard var obj = obj else { return Offset() }
    return pack(&builder, obj: &obj)
  }

  public static func pack(_ builder: inout FlatBufferBuilder, obj: inout authv1_KillSessionResponseT) -> Offset {
    let __root = authv1_KillSessionResponse.startKillSessionResponse(&builder)
    authv1_KillSessionResponse.add(ok: obj.ok, &builder)
    return authv1_KillSessionResponse.endKillSessionResponse(&builder, start: __root)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.ok.p, fieldName: "ok", required: false, type: Bool.self)
    _v.finish()
  }
}

public class authv1_KillSessionResponseT: NativeObject {

  public var ok: Bool

  public init(_ _t: borrowing authv1_KillSessionResponse) {
    ok = _t.ok
  }

  public init() {
    ok = false
  }

  public func serialize() -> ByteBuffer { return serialize(type: authv1_KillSessionResponse.self) }

}
